### ISSUE TITLE
Add macOS support

### ISSUE THREAD

**Issue by alex73630** [ultraleap/UnrealPlugin#100]
I'm working on a project where we are looking into using M1 Mac Minis instead of Intel NUCs for cost and performances reasons.

Although the current plugin doesn't support macOS, even though the SDK supports it (albeit still being compiled for Intel).

I was surprised by the Leap Motion tracking performance on the SDK's Visualizer on the M1 and I feel there is a lot of potential.

**Comment by 1OGAG** [comment]
I'm also curious about macOS support...

**Comment by Ultraleap-Dan** [comment]
Hi, currently we don't have any timescales with regards to making our Unreal Plugin available for macOS. The first step will be to enable Gemini V5 Mac Support which is currently on our roadmap for late next year. I recommend keeping an eye on our social news feeds for any announcements that we make about this.

In the meantime, it would be very helpful to learn more about your use cases and development projects so we can feed this back to our product teams to help them shape and prioritise our development roadmap.

If you can email me at support@ultraleap.com with some information about this that would be very useful and gratefully received.
