### ISSUE TITLE
how should i manipulate my AR app content as Leap motion does not work with android 

### ISSUE THREAD

**Issue by hamu6259** [ultraleap/UnrealPlugin#104]
I have  posted a query few hours ago about the issue that leap motion is not working with my android phone and i came to know that leap motion does not support android. I would like to ask the alternative for that. does any body has any clue what should i do to use it android phone while running the application on windows platform. Is it viable that i run the AR app on windows and send the data to android? does any body know anything about this, please reply.

**Comment by Ultraleap-Dan** [comment]
Hi, we have an old blog article here shows how our hand tracking data can be streamed to and Android device by using third-party software such as VRidge.

https://blog.leapmotion.com/vr-prototyping-less-100-leap-motion-vridge/

as well as a support guide on RiftCat's website:

https://support.riftcat.com/hc/en-us/articles/211680065-LeapMotion-Tutorial-Tracking-your-hands-with-VRidge

I hope this helps.

**Comment by hamu6259** [comment]
Hi, 
    Does this work for mobile AR as well as it is a description on VR handtracking?

**Comment by Ultraleap-Dan** [comment]
Hi, this will not work for mobile AR and is not supported yet.
