### ISSUE TITLE
Deal with delay in connecting to the leap Service

### ISSUE THREAD

**Issue by diekleinekuh** [ultraleap/UnrealPlugin#107]
Since the upgrade to Gemini we have an initialization issue in standalone builds. On some PCs the plugin hasn't connected to the leap service yet when the game code tries to find a device. So the game code tries to access a leap motion tracker device and fails. 

The game code currently has no way of knowing in this state if a device is simply not connected or if just the service connection hasn't been established. The code would have to wait for an unkown amount of time until the service connection is made and a DeviceAdded event will be triggered. Alternatively our app could switch to a mode without a leap tracker just to switch back immediately. 

Our app is assuming the tracker is always present and reacting to events there doesn't make a lot of sense to us. As a workaround we added a waiting loop to the place where the connection is made inside of FUltraLeapTrackingInputDevice. It would be great if the plugin would either wait itself until a service connection is being made or allow external code to do such a wait loop somewhere by exposing the IsConnected state inside of LeapWrapper.

**Comment by JimSimons-UH** [comment]
Hi diekleinekuh,

Thanks for the feedback. 

This issue is usually to do with the time at which Unreal initializes input devices, rather than the Leap Connection timing. 

If you put a short delay after beginplay (like 0.02 seconds) before checking for devices, all the state will be correct. It's the same with APIs for HMD presence. From then on, binding to device active events from the leap component will let the app know when a device is plugged/unplugged.

**Comment by diekleinekuh** [comment]
Putting in a delay to give the plugin time to update the state of devices will work. The problem with this approach is just that this just adds a delay to the system even for cases where the device isn't there or never will be. Also it isn't clear what delay will be enough. 

Also in our case the problem is really caused by the time it takes for getting a connection to the service (or the time it takes to spin up the message loop) inside of the leap plugin. If we put a loop that waits for the service to connect right after the waiting loop is started this works reliably. 

In our startup flow we want to work with the devices present. If no leap tracker is there we want to disable certain parts of the initialization routine in BeginPlay and work without it. This is mainly for making things work for Developers who do not have the leap device present. Without modifying the plugin code we can do this:

1. Put in a fixed delay as you suggested. But how long should it be? Will 200 ms always be enough. Also this might delay startup more than necessary. Fixed delays to make things work are in general not a good solution.
2. We could subscribe to ULeapComponent::OnLeapServiceDisconnected. But it might be that we will never get this message if the connection was already made before BeginPlay ran. This is were it would be really nice to have some kind of service connection status exposed like: Connecting, Connected, ConnectionFaild or something. 

I hope this makes it more clear what I'm requesting and why.

**Comment by JimSimons-UH** [comment]
thanks for the detailed description, I agree the delay after BeginPlay is not an ideal solution and is a short-term work-around. 

I've created a ticket to add a more robust solution for this scenario.

**Comment by JimSimons-UH** [comment]
Hi @diekleinekuh, the latest release fixes the beginplay/delay issue.  https://github.com/ultraleap/UnrealPlugin/releases/tag/v4.1.1
