### ISSUE TITLE
How to use Character meshes 

### ISSUE THREAD

**Issue by lytlintao** [ultraleap/UnrealPlugin#110]
How to connect the hand to the whole Character meshes? Could you explain it in detail? There is no detailed explanation in the documentation.

**Comment by JimSimons-UH** [comment]
There's some example rigged characters in the LeapUnrealModules sample project in https://github.com/leapmotion/LeapUnrealModules/tree/master/Content/Modules/Rigging.

Also see the Unreal documentation on animation blueprints and IK for more information,

**Comment by lytlintao** [comment]
Thankyou! 
Can you tell me which version of UE4 and which version of LeapUnreal is used for the LeapUnrealModules?

**Comment by JimSimons-UH** [comment]
You can use the latest release of the UnrealPlugin formerly LeapUnreal with UE 4.27, or an older release of LeapUnreal for UE 4.25 or 4.26.
