### ISSUE TITLE
Enhancement: Add support for UE5

### ISSUE THREAD

**Issue by ReadyPlayerEmma** [ultraleap/UnrealPlugin#111]
I'd really like to see UE5 support. According to the official Unreal website: "We hope to ship Unreal Engine 5 in early 2022."

I was able to manually compile it against UE5, but I am pretty sure it doesn't work correctly at the moment. Whenever the plugin is enabled, even if not used in the project at all, it refuses to package a build. I used a local GitLab runner to make sure the build process I was using was the same as what is in the projects GitLab CI config. I only changed the path to the engine to point to UE5.

I think it makes sense to get UE5 support prior to UE5 release (which should be soon) as there will likely be a lot of new folks jumping over there to play with all the new features and starting more serious projects with it. Also, I really want to play with UltraLeap in my UE5 Metahuman project xD

**Comment by JimSimons-UH** [comment]
@ReadyPlayerEmma, copying the response from the Metahumans thread: The plugin will compile, but a lot of the assets/maps and blueprints are not compatible with the early access release as they were saved in UE4.27. Assets that are saved in 4.27 don't open in UE5 Early access, at least until another early access release is made by Epic.

I've tested against Unreal 5.0 built from source (i.e. the most up to date code), and this loads the Ultraleap plugin's assets fine. This means when Epic do release the next UE5 preview, the plugin's assets will load correctly. It is planned to support UE5 upon official release.

**Comment by tinadanweb** [comment]
Hello I am looking for this too.  Hopefully there will be an option to make this happen. 
UE5 is amazing.

**Comment by frank-hs** [comment]
Hey there, how you were able to compile the plugin in UE5?

**Comment by jimsimonz** [comment]
Hi @frank-hs, with the latest UE 5 preview, it's the same steps as recompiling any plugin which is:

1 - Convert the project to a C++ project if it contains no C++ by adding any C++ file to the project via the Editor (add new C++ file)
2 - Add the UltraleapTrackingPlugin to the project's plugins folder
3 - Right click on your project's uproject file and choose 'generate visual studio project files'
4 - Open and build the solution

From then on you can open the .uproject as usual.

**Comment by Ultraleap-Dan** [comment]
UE 5 Preview 1 now works with our Unreal plugin.
