### ISSUE TITLE
Linux version?

### ISSUE THREAD

**Issue by MarioMey** [ultraleap/UnrealPlugin#114]
Isn't there a actual Linux version of the driver for modern version of Unreal? I know that there wouldn't be a lot of people that uses **Linux + Unreal + LeapMotion**... but now I'm on that condition, because I want to buy a device to use like this.

If not... what are the options to use a Leap controller inside Unreal 5.0? An unofficial one?

If there is no official / non official plugin... is it possible to write an Unreal C++ plugin using Leap SDK for Linux? How hard could it be?

**Comment by JimSimons-UH** [comment]
Hi @MarioMey, we've just rolled out Linux support in the plugin in v4.4.0.

**Comment by MarioMey** [comment]
I suppose that this doesn't need Gemini to work, does it?

Are there any features that Gemini offers that the Linux driver doesn't?

**Comment by JimSimons-UH** [comment]
It uses Gemini/the latest tracking service.

**Comment by MarioMey** [comment]
> It uses Gemini/the latest tracking service.

Sorry if I misunderstand... but Gemini is only for Windows. Also, its version is 5.6.1 and current Linux version (Leap_Motion_SDK_Linux_2.3.1) is 2.3.1. Does UnrealPlugin work with 2.3.1 or it needs a upgraded version?

**Comment by JimSimons-UH** [comment]
@MarioMey please contact support@ultraleap.com regarding obtaining the later drivers.
