### ISSUE TITLE
Unreal Examples for object interaction.

### ISSUE THREAD

**Issue by Tobe2d** [ultraleap/UnrealPlugin#121]
I downloaded the new update for 5.1
I am getting this errors when start a project after activating the plugin:
![image](https://user-images.githubusercontent.com/4099839/215072136-e42a0777-dbd4-4871-84f3-992383ac99d6.png)

On other note: Where can I get the Unreal Project Examples for object interaction?

**Comment by Ultraleap-Dan** [comment]
Hi @Tobe2d , please can you get the latest version and test opening a project with this?

If this issue persists please can you open the solution in Visual Studio and try recompiling this, then starting a new project and see if this clears the issue?
