### ISSUE TITLE
Controller tracking stops working if one (or more) controller(s) are disconnected

### ISSUE THREAD

**Issue by ZeroComfort** [ultraleap/UnrealPlugin#124]
Using Unreal 5.1 and plugin version 4.7.0.

The Steam controller tracking with the leap hands stops working if one (or more) controller(s) are disconnected.
Only after reconnecting the controllers, restarting both SteamVR and Unreal it "fixes" the issue.

I am using the unmodified LeapHandsPawn in a new "basic" level.

**Comment by Ultraleap-Dan** [comment]
Hi @ZeroComfort , please can you let us know exactly which make and model of headset and controllers you are using?

**Comment by ZeroComfort** [comment]
> Hi @ZeroComfort , please can you let us know exactly which make and model of headset and controllers you are using?

They are the Valve Index Headset and accompanying Valve Index Controllers. Also using two Valve Index Base Stations.

**Comment by Ultraleap-Dan** [comment]
Hi @ZeroComfort, please can you update to our latest hand tracking plugin version, 5.0.0, test this on Unreal 5.1 and reopen this report if any issues persist. Thank you.
