### ISSUE TITLE
Can't build a C++ project because of missing LeapC.h

### ISSUE THREAD

**Issue by demonixis** [ultraleap/UnrealPlugin#132]
Hello,
I've installed the UltraLeap plugin from the marketplace and enabled it into my project which uses Unreal 5.2.1.

I've added a reference to the plugin into my build.cs to be able to use it from C++ like this `PrivateDependencyModuleNames.Add("UltraleapTracking");`

But when I compile my project I got this error 
```
0>LeapWrapper.h(13): Error C1083 : Impossible d'ouvrir le fichier include : 'LeapC.h' : No such file or directory
```

Any clues to solve this? It works in blueprint, but I can't recompile my project. It's fine if I disable the plugin.

**Comment by Ultraleap-Dan** [comment]
Hi, please can you update your plugin version to the latest available from the UE Marketplace and retest, this should resolve the issue for you, but please let us know if any issues persist so we can help further?

**Comment by Ultraleap-Dan** [comment]
Hi, we have tested this with the latest version of our plugin and this is working correctly. We will close this issue but is you experience any further errors please can you open a new issue or contact us via support@ultraleap.com and we will be happy to help further.
