### ISSUE TITLE
Directory Access permissions corrupted in 4.11.0 release zipfiles ?

### ISSUE THREAD

**Issue by JJones780** [ultraleap/UnrealPlugin#136]
RE: The zip files containing the 4.11.0 release : UltraleapTracking_ue5_3.zip  and UltraleapTracking_ue5_2.zip  and maybe others?

20+ directories were missing access rights causing the compile to fail.

I corrected these using  `sudo find . -type d \! -perm -u=x -ls -exec chmod u+x '{}' \;`  (Linux)

Also, unzip seemed to work but my usual gui archive tool (Ark)  didn't want to reproduce the directory structures !?!

**Comment by Ultraleap-Dan** [comment]
Thank you for posting this issue. We have raised an issue to our engineering backlog to be investigated.
