### ISSUE TITLE
UE 5.3.2 Build fail using Plugin v4.12.0

### ISSUE THREAD

**Issue by Luca71** [ultraleap/UnrealPlugin#146]
Please find attached the issue from my build output log. I'm not using hands in scene, only an actor with Leap component attached to move an object around the scene.

LogClass: Error: IntProperty FLeapFrameData::NumberOfHandsVisible is not initialized properly. Module:UltraleapTracking File:Public/UltraleapTrackingData.h
LogClass: Error: IntProperty FLeapFrameData::FrameRate is not initialized properly. Module:UltraleapTracking File:Public/UltraleapTrackingData.h
LogClass: Error: IntProperty FLeapFrameData::FrameId is not initialized properly. Module:UltraleapTracking File:Public/UltraleapTrackingData.h
LogClass: Error: BoolProperty FLeapFrameData::LeftHandVisible is not initialized properly. Module:UltraleapTracking File:Public/UltraleapTrackingData.h
LogClass: Error: BoolProperty FLeapFrameData::RightHandVisible is not initialized properly. Module:UltraleapTracking File:Public/UltraleapTrackingData.h
LogClass: Error: Int64Property FLeapFrameData::TimeStamp is not initialized properly. Module:UltraleapTracking File:Public/UltraleapTrackingData.h
LogClass: Error: StructProperty FLeapFrameData::FinalRotationAdjustment is not initialized properly. Module:UltraleapTracking File:Public/UltraleapTrackingData.h
LogClass: Error: FloatProperty FLeapHandData::Confidence is not initialized properly. Module:UltraleapTracking File:Public/UltraleapTrackingData.h
LogClass: Error: IntProperty FLeapHandData::Flags is not initialized properly. Module:UltraleapTracking File:Public/UltraleapTrackingData.h
LogClass: Error: FloatProperty FLeapHandData::GrabAngle is not initialized properly. Module:UltraleapTracking File:Public/UltraleapTrackingData.h
LogClass: Error: FloatProperty FLeapHandData::GrabStrength is not initialized properly. Module:UltraleapTracking File:Public/UltraleapTrackingData.h
LogClass: Error: ByteProperty FLeapHandData::HandType is not initialized properly. Module:UltraleapTracking File:Public/UltraleapTrackingData.h
LogClass: Error: FloatProperty FLeapHandData::PinchDistance is not initialized properly. Module:UltraleapTracking File:Public/UltraleapTrackingData.h
LogClass: Error: FloatProperty FLeapHandData::PinchStrength is not initialized properly. Module:UltraleapTracking File:Public/UltraleapTrackingData.h
LogClass: Error: IntProperty FLeapHandData::Id is not initialized properly. Module:UltraleapTracking File:Public/UltraleapTrackingData.h
LogClass: Error: FloatProperty FLeapHandData::VisibleTime is not initialized properly. Module:UltraleapTracking File:Public/UltraleapTrackingData.h
LogClass: Error: IntProperty FLeapDigitData::FingerId is not initialized properly. Module:UltraleapTracking File:Public/UltraleapTrackingData.h
LogClass: Error: BoolProperty FLeapDigitData::IsExtended is not initialized properly. Module:UltraleapTracking File:Public/UltraleapTrackingData.h
LogClass: Error: StructProperty FLeapBoneData::PrevJoint is not initialized properly. Module:UltraleapTracking File:Public/UltraleapTrackingData.h
LogClass: Error: StructProperty FLeapBoneData::NextJoint is not initialized properly. Module:UltraleapTracking File:Public/UltraleapTrackingData.h
LogClass: Error: StructProperty FLeapBoneData::Rotation is not initialized properly. Module:UltraleapTracking File:Public/UltraleapTrackingData.h
LogClass: Error: FloatProperty FLeapBoneData::Width is not initialized properly. Module:UltraleapTracking File:Public/UltraleapTrackingData.h
LogClass: Error: StructProperty FLeapPalmData::Direction is not initialized properly. Module:UltraleapTracking File:Public/UltraleapTrackingData.h
LogClass: Error: StructProperty FLeapPalmData::Normal is not initialized properly. Module:UltraleapTracking File:Public/UltraleapTrackingData.h
LogClass: Error: StructProperty FLeapPalmData::Orientation is not initialized properly. Module:UltraleapTracking File:Public/UltraleapTrackingData.h
LogClass: Error: StructProperty FLeapPalmData::Position is not initialized properly. Module:UltraleapTracking File:Public/UltraleapTrackingData.h
LogClass: Error: StructProperty FLeapPalmData::StabilizedPosition is not initialized properly. Module:UltraleapTracking File:Public/UltraleapTrackingData.h
LogClass: Error: StructProperty FLeapPalmData::Velocity is not initialized properly. Module:UltraleapTracking File:Public/UltraleapTrackingData.h
LogClass: Error: FloatProperty FLeapPalmData::Width is not initialized properly. Module:UltraleapTracking File:Public/UltraleapTrackingData.h
LogClass: Error: IntProperty FBodyStateDevice::DeviceId is not initialized properly. Module:BodyState File:Public/BodyStateDevice.h
LogClass: Error: EnumProperty FNamedBoneData::Name is not initialized properly. Module:BodyState File:Public/Skeleton/BodyStateSkeleton.h
LogClass: Error: EnumProperty FKeyedTransform::Name is not initialized properly. Module:BodyState File:Public/Skeleton/BodyStateSkeleton.h
LogClass: Error: EnumProperty FNamedBoneMeta::Name is not initialized properly. Module:BodyState File:Public/Skeleton/BodyStateSkeleton.h
LogClass: Error: IntProperty FLeapDevice::Baseline is not initialized properly. Module:UltraleapTracking File:Public/UltraleapTrackingData.h
LogClass: Error: FloatProperty FLeapDevice::HorizontalFOV is not initialized properly. Module:UltraleapTracking File:Public/UltraleapTrackingData.h
LogClass: Error: FloatProperty FLeapDevice::VerticalFOV is not initialized properly. Module:UltraleapTracking File:Public/UltraleapTrackingData.h
LogClass: Error: IntProperty FLeapDevice::Range is not initialized properly. Module:UltraleapTracking File:Public/UltraleapTrackingData.h
LogClass: Display: 37 Uninitialized script struct members found including 0 object properties
LogAutomationTest: Error: UObject.Class AttemptToFindUninitializedScriptStructMembers will be marked as failing due to errors being logged
LogAutomationTest: Error: LogClass: IntProperty FLeapFrameData::NumberOfHandsVisible is not initialized properly. Module:UltraleapTracking File:Public/UltraleapTrackingData.h
LogAutomationTest: Error: LogClass: IntProperty FLeapFrameData::FrameRate is not initialized properly. Module:UltraleapTracking File:Public/UltraleapTrackingData.h
LogAutomationTest: Error: LogClass: IntProperty FLeapFrameData::FrameId is not initialized properly. Module:UltraleapTracking File:Public/UltraleapTrackingData.h
LogAutomationTest: Error: LogClass: BoolProperty FLeapFrameData::LeftHandVisible is not initialized properly. Module:UltraleapTracking File:Public/UltraleapTrackingData.h
LogAutomationTest: Error: LogClass: BoolProperty FLeapFrameData::RightHandVisible is not initialized properly. Module:UltraleapTracking File:Public/UltraleapTrackingData.h
LogAutomationTest: Error: LogClass: Int64Property FLeapFrameData::TimeStamp is not initialized properly. Module:UltraleapTracking File:Public/UltraleapTrackingData.h
LogAutomationTest: Error: LogClass: StructProperty FLeapFrameData::FinalRotationAdjustment is not initialized properly. Module:UltraleapTracking File:Public/UltraleapTrackingData.h
LogAutomationTest: Error: LogClass: FloatProperty FLeapHandData::Confidence is not initialized properly. Module:UltraleapTracking File:Public/UltraleapTrackingData.h
LogAutomationTest: Error: LogClass: IntProperty FLeapHandData::Flags is not initialized properly. Module:UltraleapTracking File:Public/UltraleapTrackingData.h
LogAutomationTest: Error: LogClass: FloatProperty FLeapHandData::GrabAngle is not initialized properly. Module:UltraleapTracking File:Public/UltraleapTrackingData.h
LogAutomationTest: Error: LogClass: FloatProperty FLeapHandData::GrabStrength is not initialized properly. Module:UltraleapTracking File:Public/UltraleapTrackingData.h
LogAutomationTest: Error: LogClass: ByteProperty FLeapHandData::HandType is not initialized properly. Module:UltraleapTracking File:Public/UltraleapTrackingData.h
LogAutomationTest: Error: LogClass: FloatProperty FLeapHandData::PinchDistance is not initialized properly. Module:UltraleapTracking File:Public/UltraleapTrackingData.h
LogAutomationTest: Error: LogClass: FloatProperty FLeapHandData::PinchStrength is not initialized properly. Module:UltraleapTracking File:Public/UltraleapTrackingData.h
LogAutomationTest: Error: LogClass: IntProperty FLeapHandData::Id is not initialized properly. Module:UltraleapTracking File:Public/UltraleapTrackingData.h
LogAutomationTest: Error: LogClass: FloatProperty FLeapHandData::VisibleTime is not initialized properly. Module:UltraleapTracking File:Public/UltraleapTrackingData.h
LogAutomationTest: Error: LogClass: IntProperty FLeapDigitData::FingerId is not initialized properly. Module:UltraleapTracking File:Public/UltraleapTrackingData.h
LogAutomationTest: Error: LogClass: BoolProperty FLeapDigitData::IsExtended is not initialized properly. Module:UltraleapTracking File:Public/UltraleapTrackingData.h
LogAutomationTest: Error: LogClass: StructProperty FLeapBoneData::PrevJoint is not initialized properly. Module:UltraleapTracking File:Public/UltraleapTrackingData.h
LogAutomationTest: Error: LogClass: StructProperty FLeapBoneData::NextJoint is not initialized properly. Module:UltraleapTracking File:Public/UltraleapTrackingData.h
LogAutomationTest: Error: LogClass: StructProperty FLeapBoneData::Rotation is not initialized properly. Module:UltraleapTracking File:Public/UltraleapTrackingData.h
LogAutomationTest: Error: LogClass: FloatProperty FLeapBoneData::Width is not initialized properly. Module:UltraleapTracking File:Public/UltraleapTrackingData.h
LogAutomationTest: Error: LogClass: StructProperty FLeapPalmData::Direction is not initialized properly. Module:UltraleapTracking File:Public/UltraleapTrackingData.h
LogAutomationTest: Error: LogClass: StructProperty FLeapPalmData::Normal is not initialized properly. Module:UltraleapTracking File:Public/UltraleapTrackingData.h
LogAutomationTest: Error: LogClass: StructProperty FLeapPalmData::Orientation is not initialized properly. Module:UltraleapTracking File:Public/UltraleapTrackingData.h
LogAutomationTest: Error: LogClass: StructProperty FLeapPalmData::Position is not initialized properly. Module:UltraleapTracking File:Public/UltraleapTrackingData.h
LogAutomationTest: Error: LogClass: StructProperty FLeapPalmData::StabilizedPosition is not initialized properly. Module:UltraleapTracking File:Public/UltraleapTrackingData.h
LogAutomationTest: Error: LogClass: StructProperty FLeapPalmData::Velocity is not initialized properly. Module:UltraleapTracking File:Public/UltraleapTrackingData.h
LogAutomationTest: Error: LogClass: FloatProperty FLeapPalmData::Width is not initialized properly. Module:UltraleapTracking File:Public/UltraleapTrackingData.h
LogAutomationTest: Error: LogClass: IntProperty FBodyStateDevice::DeviceId is not initialized properly. Module:BodyState File:Public/BodyStateDevice.h
LogAutomationTest: Error: LogClass: EnumProperty FNamedBoneData::Name is not initialized properly. Module:BodyState File:Public/Skeleton/BodyStateSkeleton.h
LogAutomationTest: Error: LogClass: EnumProperty FKeyedTransform::Name is not initialized properly. Module:BodyState File:Public/Skeleton/BodyStateSkeleton.h
LogAutomationTest: Error: LogClass: EnumProperty FNamedBoneMeta::Name is not initialized properly. Module:BodyState File:Public/Skeleton/BodyStateSkeleton.h
LogAutomationTest: Error: LogClass: IntProperty FLeapDevice::Baseline is not initialized properly. Module:UltraleapTracking File:Public/UltraleapTrackingData.h
LogAutomationTest: Error: LogClass: FloatProperty FLeapDevice::HorizontalFOV is not initialized properly. Module:UltraleapTracking File:Public/UltraleapTrackingData.h
LogAutomationTest: Error: LogClass: FloatProperty FLeapDevice::VerticalFOV is not initialized properly. Module:UltraleapTracking File:Public/UltraleapTrackingData.h
LogAutomationTest: Error: LogClass: IntProperty FLeapDevice::Range is not initialized properly. Module:UltraleapTracking File:Public/UltraleapTrackingData.h

**Comment by Ultraleap-Dan** [comment]
Hi, please can you update the plugin that you are using to the latest version and retest?

https://github.com/ultraleap/UnrealPlugin/releases/tag/v5.0.1

If the issue persists please can you let us know and we can investigate further.

**Comment by Luca71** [comment]
Hi, Before your reply I resolved the issue transforming the UE project in C++ project adding new C++ empty Class. Then I compiled the project from visual studio, and now I'm able to build succesfully.
